/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Shoe = IDL.Record({
  'id' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Nat),
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addShoe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Nat),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Shoe)], ['query']),
  'getAllShoes' : IDL.Func([], [IDL.Vec(Shoe)], ['query']),
  'getShoe' : IDL.Func([IDL.Text], [Shoe], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Shoe = IDL.Record({
    'id' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Nat),
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addShoe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Shoe)], ['query']),
    'getAllShoes' : IDL.Func([], [IDL.Vec(Shoe)], ['query']),
    'getShoe' : IDL.Func([IDL.Text], [Shoe], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };